var annotated_dup =
[
    [ "AdaptiveSparseGrid", "class_adaptive_sparse_grid.html", "class_adaptive_sparse_grid" ],
    [ "AdaptiveSparseGrid_Base", "class_adaptive_sparse_grid___base.html", "class_adaptive_sparse_grid___base" ],
    [ "ConstantCoefficientMass", "class_constant_coefficient_mass.html", null ],
    [ "Exp_Functor", "class_exp___functor.html", null ],
    [ "IndexOneD", "class_index_one_d.html", "class_index_one_d" ],
    [ "IntCases", "class_int_cases.html", null ],
    [ "IntegratorHelm", "class_integrator_helm.html", "class_integrator_helm" ],
    [ "IntegratorHelmConstant", "class_integrator_helm_constant.html", "class_integrator_helm_constant" ],
    [ "IntegratorPoisson", "class_integrator_poisson.html", "class_integrator_poisson" ],
    [ "IntegratorPoissonCurved", "class_integrator_poisson_curved.html", "class_integrator_poisson_curved" ],
    [ "IntegratorRHS", "class_integrator_r_h_s.html", "class_integrator_r_h_s" ],
    [ "InterfaceLocalStiffnessMatrices", "class_interface_local_stiffness_matrices.html", "class_interface_local_stiffness_matrices" ],
    [ "ListOfDepthOrderedSubgrids", "class_list_of_depth_ordered_subgrids.html", null ],
    [ "LocalForTensor", "class_local_for_tensor.html", "class_local_for_tensor" ],
    [ "MatrixVectorHomogen", "class_matrix_vector_homogen.html", "class_matrix_vector_homogen" ],
    [ "MaxShift", "class_max_shift.html", null ],
    [ "MaxShiftFive", "class_max_shift_five.html", null ],
    [ "MultiDimCompass", "class_multi_dim_compass.html", null ],
    [ "MultiDimFiveCompass", "class_multi_dim_five_compass.html", null ],
    [ "MultiDimTwoCompass", "class_multi_dim_two_compass.html", null ],
    [ "RectangularIterator", "class_rectangular_iterator.html", "class_rectangular_iterator" ],
    [ "ShiftExpr", "class_shift_expr.html", null ],
    [ "ShiftOperator", "class_shift_operator.html", "class_shift_operator" ],
    [ "SimpleMultiHash", "class_simple_multi_hash.html", "class_simple_multi_hash" ],
    [ "SimpleVector", "class_simple_vector.html", "class_simple_vector" ],
    [ "Static_IndexOneD", "class_static___index_one_d.html", "class_static___index_one_d" ],
    [ "SubgridFixedDepth", "class_subgrid_fixed_depth.html", "class_subgrid_fixed_depth" ],
    [ "VariableCoefficientMass", "class_variable_coefficient_mass.html", "class_variable_coefficient_mass" ]
];