name: Build and Publish Doxygen Docs

on:
  push:
    branches:
      - main

      
permissions:
  contents: write  

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required to push to another branch

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate documentation
        working-directory: ./docs
        run: doxygen Doxyfile

      - name: Deploy HTML docs to doxygen-html branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: doxygen-html   # <-- your separate branch for HTML output
          publish_dir: ./docs/html       # <-- adjust if Doxygen outputs elsewhere
          commit_message: "Update Doxygen HTML docs from main"
