name: Update Doxygen Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Doxygen
        uses: ssciwr/doxygen-install@v1

      - name: Generate Doxygen documentation
        run: doxygen docs/Doxyfile

      - name: Deploy to doxygen-docs branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: doxygen-docs
          publish_dir: ./docs/html
          force_orphan: true
